fs = 1000;
t = 0:1/fs:250;
f = 1/100;
m = sin(2*pi*f*t);
c = (square(t) + 1)/2;
s = m.*c;
subplot(3,1,1);
plot(t,m);
xlabel("t");
ylabel("Amplitude");
title("Pulse Amplitude Modulation");
subplot(3,1,2);
plot(t,c);
xlabel("t");
ylabel("Amplitude");
subplot(3,1,3);
plot(t,s);
xlabel("t");
ylabel("Amplitude");
